In [3]:
# Load dplyr
library(dplyr)
library(readxl)

Installing package into 'C:/Users/Janani/AppData/Local/R/win-library/4.4'
(as 'lib' is unspecified)

package 'readxl' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Janani\AppData\Local\Temp\Rtmp8qUB56\downloaded_packages

Warning message:
"package 'readxl' was built under R version 4.4.3"

In [2]:
wis <- read.csv("wcld.csv",, header = TRUE)
head(wis)
colnames(wis)

  county new_id sex race             judge_id case_type
1 40      3     M   African American  436     Felony
2 30      6     M   Caucasian        1049     Misdemeanor
3 30      7     M   African American 1009     Misdemeanor
4 30     12     M   Caucasian         232     Criminal Traffic
5 40     17     M   African American  694     Criminal Traffic
6 67     17     M   African American 1175     Misdemeanor
  wcisclass                   age_offense age_judge prior_felony ⋯
1 Drug Possession             40          41        0            ⋯
2 Disorderly Conduct          39          40        0            ⋯
3 Resisting Officer           17          17        0            ⋯
4 Operating While Intoxicated 65          65        0            ⋯
5 OAR/OAS                     51          51        1            ⋯
6 Drug Possession             55          55        1            ⋯
  prior_charges_severity19 prior_charges_severity20 prior_charges_severity21
1 0                        0                        0
2 0                        0                        0
3 0                        0                        0
4 0                        0                        0
5 0                        0                        0
6 0                        0                        0
  max_hist_jail min_hist_jail avg_hist_jail median_hist_jail
1  0             0             0             0
2  0             0             0             0
3  0             0             0             0
4  0             0             0             0
5 NA            NA            NA            NA
6 NA            NA            NA            NA
  all_races                  violent_crime recid_180d_violent
1 African American           0             0
2 Caucasian                  0             0
3 African American           0             0
4 Caucasian                  0             0
5 African American,Caucasian 0             0
6 African American,Caucasian 0             0

 [1] "county"                     "new_id"
 [3] "sex"                        "race"
 [5] "judge_id"                   "case_type"
 [7] "wcisclass"                  "age_offense"
 [9] "age_judge"                  "prior_felony"
[11] "prior_misdemeanor"          "prior_criminal_traffic"
[13] "highest_severity"           "release"
[15] "probation"                  "is_recid_new"
[17] "recid_180d"                 "zip"
[19] "pct_black"                  "pct_hisp"
[21] "pct_male"                   "pct_rural"
[23] "pct_urban"                  "pct_college"
[25] "pct_food_stamps"            "pop_dens"
[27] "pct_somecollege"            "med_hhinc"
[29] "year"                       "jail"
[31] "train_test_split_caselevel" "train_test_split_deflevel"
[33] "prior_charges_severity7"    "prior_charges_severity8"
[35] "prior_charges_severity9"    "prior_charges_severity10"
[37] "prior_charges_severity11"   "prior_charges_severity12"
[39] "prior_charges_severity13"   "prior_charges_severity14"
[41] "prior_charges_severity15"   "prior_charges_severity16"
[43] "prior_charges_severity17"   "prior_charges_severity18"
[45] "prior_charges_severity19"   "prior_charges_severity20"
[47] "prior_charges_severity21"   "max_hist_jail"
[49] "min_hist_jail"              "avg_hist_jail"
[51] "median_hist_jail"           "all_races"
[53] "violent_crime"              "recid_180d_violent"

ERROR: Error in read_excel("Wisconsin County-FIPS mapping.xlsx"): could not find function "read_excel"

In [4]:
county <-  read_excel("Wisconsin County-FIPS mapping.xlsx")
head(county)

  County Code County Name FIPS Code
1 1           Adams       55001
2 2           Ashland     55003
3 3           Barron      55005
4 4           Bayfield    55007
5 5           Brown       55009
6 6           Buffalo     55011

In [7]:
# Perform left join
merged_data <- wis %>%
  left_join(county, by = c("county" = "County Code"))

#Rename FIPS and County name columns
merged_data <- merged_data %>%
  rename(
    County_Name = `County Name`,
    FIPS = `FIPS Code`
  )

# View the result
head(merged_data)

  county new_id sex race             judge_id case_type
1 40      3     M   African American  436     Felony
2 30      6     M   Caucasian        1049     Misdemeanor
3 30      7     M   African American 1009     Misdemeanor
4 30     12     M   Caucasian         232     Criminal Traffic
5 40     17     M   African American  694     Criminal Traffic
6 67     17     M   African American 1175     Misdemeanor
  wcisclass                   age_offense age_judge prior_felony ⋯
1 Drug Possession             40          41        0            ⋯
2 Disorderly Conduct          39          40        0            ⋯
3 Resisting Officer           17          17        0            ⋯
4 Operating While Intoxicated 65          65        0            ⋯
5 OAR/OAS                     51          51        1            ⋯
6 Drug Possession             55          55        1            ⋯
  prior_charges_severity21 max_hist_jail min_hist_jail avg_hist_jail
1 0                         0             0             0
2 0                         0             0             0
3 0                         0             0             0
4 0                         0             0             0
5 0                        NA            NA            NA
6 0                        NA            NA            NA
  median_hist_jail all_races                  violent_crime recid_180d_violent
1  0               African American           0             0
2  0               Caucasian                  0             0
3  0               African American           0             0
4  0               Caucasian                  0             0
5 NA               African American,Caucasian 0             0
6 NA               African American,Caucasian 0             0
  County_Name FIPS
1 Milwaukee   55079
2 Kenosha     55059
3 Kenosha     55059
4 Kenosha     55059
5 Milwaukee   55079
6 Waukesha    55133

In [11]:
#Checking missing values in FIPS column
sum(is.na(merged_data$FIPS))
any(is.na(merged_data$FIPS))
any(is.na(merged_data$County_name))

[1] 0

[1] FALSE

[1] FALSE

- There are no missing values in FIPS Column or County names column

In [12]:
#Write data
write.csv(merged_data, "main_merged_data_FIPS.csv", row.names = FALSE)